import {
  Geist,
  Geist_Mono,
  Syne,
  Montserrat,
  Noto_Sans_JP,
} from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/Providers";

// 必要なフォントをここで全て定義します
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const syne = Syne({
  variable: "--font-syne",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const notoSansJP = Noto_Sans_JP({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                function getInitialTheme() {
                  const storedTheme = localStorage.getItem('theme');
                  if (storedTheme) return storedTheme;
                  return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
                }
                const theme = getInitialTheme();
                if (theme === 'dark') {
                  document.documentElement.classList.add('dark');
                }
              })();
            `,
          }}
        />
        {/* ✅ Google サイト認証用 meta タグ */}
        <meta
          name="google-site-verification"
          content="g2LnGPTFyxNO74UktP7IKZQfYqU5U7iC49-NtHpQB8U"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${syne.variable} ${montserrat.variable} ${notoSansJP.className} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
