import {
  Geist,
  Geist_Mono,
  Syne,
  Montserrat,
  Noto_Sans_JP,
} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const syne = Syne({
  variable: "--font-syne",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

// 変更：Noto Sans JPをデフォルトフォントとして設定
const notoSansJP = Noto_Sans_JP({
  subsets: ["latin"], // これなら通る
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* ✅ Google サイト認証用 meta タグ */}
        <meta
          name="google-site-verification"
          content="g2LnGPTFyxNO74UktP7IKZQfYqU5U7iC49-NtHpQB8U"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${syne.variable} ${montserrat.variable} ${notoSansJP.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
